import pygame
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 400
MOUSE_CONSTANT = 500
GRAVITY = 1
FLOOR_PLANE = 300
PLAYER_STARTING_X = 150
SNAIL_SPEED = 6
SNAIL_SCREEN_DISTANCE = 100
OBSTACLE_TIMER = pygame.USEREVENT + 1
ENEMY_ANIMATION_TIMER = OBSTACLE_TIMER + 1